name: Auto Share Tailscale Machine

on:
  workflow_dispatch:

jobs:
  share:
    runs-on: ubuntu-latest

    env:
      TAILSCALE_AUTHKEY: tskey-auth-kErqicdzCC11CNTRL-zUAhdTpBoaXBn3BzpzszaXEAgqBZk2iRB
      SHARE_EMAIL: trongphucpython@gmail.com
      MACHINE_NAME: gh-runner-24227352594

    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect Tailscale
        run: |
          sudo tailscale up --authkey=$TAILSCALE_AUTHKEY --hostname=gh-actions

      - name: Get machine list
        run: |
          tailscale status --json > status.json

      - name: Find node ID
        run: |
          python3 find_node.py

      - name: Share machine
        run: |
          NODE_ID=$(cat node.txt)

          if [ -z "$NODE_ID" ]; then
            echo "❌ Machine not found"
            exit 1
          fi

          tailscale share "$NODE_ID" "$SHARE_EMAIL"
